
name: Broken Action 2 - Create an issue

on:
  pull_request: 
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:

      - name: Hello World
        run: echo "hello world"

      - name: Checkout files
        uses: actions/checkout@v3

      - name: Create An Issue
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: ./utils/issue-template.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}